version: '1'
services:
  sql-azure:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password@1234"
      ACCEPT_EULA: "Y"
    networks:
      - app-network
    hostname: sqlazure  # Set the hostname to make it accessible via this name

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    hostname: rabbitmq

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - app-network
    hostname: loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - loki

  rest-service:
    image: frankawesome/tuncrest-4:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - sql-azure
      - rabbitmq
    hostname: rest-service  # Set the hostname to make it accessible via this name

  node:
    image: frankawesome/tuncnode-4:latest
    networks:
      - app-network
    depends_on:
      - rabbitmq

networks:
  app-network:
